### ISSUE TITLE
Commencer a reflechir aux UnitTest

### ISSUE THREAD

**Issue by Elodieprog** [EPFL-SV-cpp-projects/Team_15#12]
Unitests de réaction (taux)

pas besoin de faire UnitTests de random

**Comment by bissay** [comment]
UnitTests de random (si cela fonctionne)
UnitTests de réaction (bon calcul des taux)

**Comment by bissay** [comment]
Il y a eu changement de conceptions du projet; nouvelles idées de UnitTests dans une autre tâche.
