### ISSUE TITLE
Nombres aléatoires et distributions

### ISSUE THREAD

**Issue by vnigolian** [EPFL-SV-cpp-projects/Team_15#3]
Ecrire une classe permettant de générer des nombres et des distributions aléatoires.

**Comment by aequey** [comment]
Maybe still a few tests to write (that check other things than extreme values), but I'm not sure how to do it.

**Comment by vnigolian** [comment]
Looks good.
See if you can use the same generator and random_device in all methods instead of creating new ones every time.
