### ISSUE TITLE
Class reaction chimique a finir en binome 1/2

### ISSUE THREAD

**Issue by Elodieprog** [EPFL-SV-cpp-projects/Team_15#7]
Faire en binome tous le polymorphisme, et donc toute la hiérarchie des réactions chimique. Il s'en suit qu'il faut crééer de nouvelles sous classes: inibition, activation et chacune d'elle aura d'autres sous classe selon si le reactif est une proteine, un ARN ou un gene.

**Comment by Alicia-max** [comment]
Nouvelle hiérarchisation de la classes Reactions : creation de 6 sous classes définissant les types de reactions possible s'appliquant  sur un gene .
