### ISSUE TITLE
Classe Reaction chimique à faire en binome 2/2

### ISSUE THREAD

**Issue by Elodieprog** [EPFL-SV-cpp-projects/Team_15#8]
En plus de reconstruire et programmer les reactions chimiques, gerer les régulations. (sous classe de reaction chimique, ou méthode... en cours de reflexion).

**Comment by Alicia-max** [comment]
Nouvelle hiérarchisation de la classe Reactions : creations de 6 nouvelles sous classe décrivant chaque type de reactions. Coder le corps des méthodes définis dans reactions et redéfinis dans les sous classes .
